# Generated by Django 4.0.1 on 2022-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadComplains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('imageLocation', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
            ],
        ),
    ]
