# Generated by Django 4.0.1 on 2022-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoadClassification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadcomplains',
            name='image',
            field=models.ImageField(default='./12.jpg', upload_to='recieved'),
        ),
        migrations.AlterField(
            model_name='roadcomplains',
            name='imageLocation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='roadcomplains',
            name='score',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
